spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://kbss.felk.cvut.cz:5433/ear2022zs_9
spring.datasource.username=ear2022zs_9
spring.datasource.password=kTBD8kaGE21kYKXZQpWAD9N

spring.jpa.generate-ddl=true
eclipselink.ddl-generation=create-tables
spring.thymeleaf.enabled=true
spring.security.user.password= root
logging.level.org.springframework.security=debug

server.servlet.session.timeout=1800
#spring.security.oauth2.client.registration.github.client-id=dfd81bd654e2167097fc
#spring.security.oauth2.client.registration.github.client-secret=459089507a3e1d7afdbbddb165034a2b385a5834
